User:
  pushToken:
    type: string
  Trip: # Collection
    destination:
      type: string
    startDate:
      type: Timestamp  
    endDate:
      type: Timestamp  
    Item: # Collection
      name:
        type: string
      reminderInterval:
        type: number  
      lastNotifiedAt:
        type: Timestamp  
      isNotifyEnabled:
        type: boolean  
      lastConfirmedAt:
        type: Timestamp  
      status:
        type: string | undefined
        enum:
          - checked
          - unchecked
          - lost
